volumes:
  oida_volume:
services:
  OidaContainer:
    image: webdevops/php-nginx:8.3
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "9022:80"

  database:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - oida_volume:/var/lib/mysql
    ports:
      - "3678:3306"
